name: generate snake animation

on:
  # läuft automatisch alle 24 Stunden
  schedule:
    - cron: "0 0 * * *"
  # erlaubt manuelles Auslösen im Actions-Tab
  workflow_dispatch:
  # läuft bei jedem Push auf main
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: slow down animation by 50%
        run: |
          perl -pi -e 's/(\d+)ms/($1*2)."ms"/ge' dist/github-contribution-grid-snake.svg dist/github-contribution-grid-snake-dark.svg

      - uses: actions/upload-artifact@v5
        with:
          name: github-contribution-grid-snake.svg
          path: dist/github-contribution-grid-snake.svg

      - name: push svg to output branch
        uses: crazy-max/ghaction-github-pages@v5
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
